[Theme]
# We won't use a wallpaper from the theme itself to ensure pure black.
# The `theme.sh` script will be responsible for setting a wallpaper if needed.
background="#000000"
# Default font to JetBrains Mono
font="JetBrains Mono"
