# Terminal Noir keybindings.

$mainMod = SUPER
$scripts = ~/.config/hypr/scripts

bind = $mainMod, T, exec, kitty
bind = $mainMod, Space, exec, ~/.local/bin/tnctl rofi apps
bind = $mainMod, slash, exec, $scripts/keybinds.sh
bind = $mainMod CTRL, L, exec, $scripts/lockscreen.sh
bind = $mainMod, M, exec, $scripts/logoutlaunch.sh
bind = $mainMod, V, exec, ~/.local/bin/tnctl clipboard open

bind = $mainMod, Q, killactive,
bind = $mainMod SHIFT, V, togglefloating,
bind = $mainMod, F, fullscreen,

bind = , Print, exec, ~/.local/bin/tnctl screenshot menu
bind = $mainMod SHIFT, P, exec, hyprpicker -an

bindl = , XF86AudioMute, exec, $scripts/volumecontrol.sh output mute
bindl = , XF86AudioLowerVolume, exec, $scripts/volumecontrol.sh output down
bindl = , XF86AudioRaiseVolume, exec, $scripts/volumecontrol.sh output up

bindl = , XF86MonBrightnessDown, exec, $scripts/brightnesscontrol.sh down
bindl = , XF86MonBrightnessUp, exec, $scripts/brightnesscontrol.sh up

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
